# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libsdl2-dev
  
# Only watch the master branch
branches:
  only:
    - master

# Build steps
script:
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake .. && make
