# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

# Install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libsdl2-dev
  
# Only watch the master branch
branches:
  only:
    - master

# Build steps
script:
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake .. && make
